// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://metllhfplaruemagjfnb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ldGxsaGZwbGFydWVtYWdqZm5iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0NjE5NjIsImV4cCI6MjA3MzAzNzk2Mn0.Aw7SQTg3upYcz1wxPBIQtI87UkY04V4JB7PLiliHEbQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});